version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-api-python
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pdfdb
    volumes:
      - ./app:/app/app
      - geoip-data:/app/data  # Add persistent volume for GeoIP data
    restart: "no"

  postgres:
    image: postgres:16
    container_name: pdf-postgres-python
    ports:
      - "5432:5432"  # Changed to 5432 to avoid conflict with Java version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdfdb
    volumes:
      - postgres-data-python:/var/lib/postgresql/data
    restart: "no"

volumes:
  postgres-data-python:
  geoip-data:  # Define the new volume for GeoIP data