version: '3.8'

services:
  app:
    build: .
    container_name: pdf-backend-python
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pdfdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: pdfdb
      JWT_SECRET: 4d6f1510466046735ec2c855e541668418711e42ca14d97bbc72063c7561babdc2d79646710a7d998b9214253cb70172150ab5cd2b220a152d3f1bcde3e800d1
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      JWT_REFRESH_TOKEN_EXPIRE_MINUTES: 10080
      PROJECT_NAME: "PDF Processing API"
      API_V1_STR: /api
    volumes:
      - ./app:/app/app
    restart: "no"

  postgres:
    image: postgres:16
    container_name: pdf-postgres-python
    ports:
      - "5433:5432"  # Changed to 5433 to avoid conflict with Java version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdfdb
    volumes:
      - postgres-data-python:/var/lib/postgresql/data
    restart: "no"

volumes:
  postgres-data-python:
